---
- hosts: all
  become: true
  tasks: 
    - name: Update all packages
      community.general.pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_facts['os_family'] == 'Archlinux'
    - name: Update all packages
      community.general.apt:
        update_cache: yes
        upgrade: yes
      when: ansible_facts['os_family'] == 'Debian'