- hosts: "*"
  become: yes
  tasks:
    - name: pacman update
      community.general.pacman:
        update_cache: yes
        upgrade: yes

    - name: upgrade yay AUR packages
      kewlfft.aur.aur:
        upgrade: yes
        use: yay
        aur_only: yes

    - name: install opera
      community.general.pacman:
        name: opera
        state: present
