controllers:
  hosts:
    # amaz-1.taila7299.ts.net:
    #  ansible_ssh_key: "~/.ssh/dadabook-air.pem"

players:
  hosts:
    oracle.taila7299.ts.net:
      ansible_ssh_key: "~/.ssh/ansible"
      ansible_user: ubuntu

storage:
  hosts: 
    oracle.taila7299.ts.net:
      ansible_ssh_key: "~/.ssh/ansible"
      ansible_user: ubuntu

dockerlab:
  children:
    controllers:
    players:
    storage:

