---
- name: run apt update and apt upgrade
  apt:
    update_cache: yes
    upgrade: yes

- name: Check if reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_md5: no
  register: reboot_required_file

- name: Reboot if required
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists

- name: Remove dependencies no loner required after boot
  ansible.builtin.apt:
    autoremove: yes
