---
- name: create a radarr container
  docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    env:
      PUID: "{{ puid }}" # var puid
      PGID: "{{ pgid }}" # var pgid
      TZ: "{{ timezone }}" # var timezone
    volumes:
      - "{{ config_dir }}/radarr:/config" # var config_dir
      - "{{ data_dir }}:/data" # vars data_dir
    ports:
      - 7878:7878
    restart_policy: unless-stopped
    restart: true
    networks:
      - name: "{{ vpn_network }}" # var vpn_network
