---
- hosts: dockerlab
  tasks:
    - name: "test if dash.net alreadyexists"
      docker_network_info:
        name: "{{ dashnet }}"
      register: dashnet_result

    - name: "create dash.net network if not exists"
      docker_network:
        name: "{{ dashnet }}"
      when: dashnet_result.exists == false

    - name: "deploy dash. container"
      docker_container:
        name: "dashdot"
        image: "mauricenino/dashdot:latest"
        restart: true
        restart_policy: "unless-stopped"
        ports:
          - 3001:3001
        volumes:
          - "/:/mnt/host:ro"
        networks:
          - name: "{{ dashnet }}"
        state: "{{ state }}"
        env:
          PUID: "{{ puid }}"
          PGID: "{{ pgid }}"
          TZ: "{{ timezone }}"
