---
- hosts: dockerlab 

  tasks:
    - name: create folder config_root_dir if not exists
      file:  
        path: "{{ config_root_dir }}"
        state: directory
        mode: '755'

    - name: create bind mounts directory homepage first to avoid conflicting permissions
      file:
        path: "{{ config_root_dir }}/homepage"
        state: directory
        mode: '755'

    - name: deploy homepage container
      docker_container:
        name: homepage
        image: "ghcr.io/gethomepage/homepage:latest"
        restart: "{{ restart }}"
        recreate: "{{ recreate }}"
        restart_policy: "unless-stopped"
        ports:
          - 80:3000
        volumes:
          - "{{ config_root_dir }}/homepage:/config"
          - /var/run/docker.sock:/var/run/docker.soc # security issue - can we avoid?
        env:
          PUID: "{{ puid }}"
          PGID: "{{ pgid }}" 
          TZ: "{{ timezone }}"
        state: "{{ state }}"

    - name: Get infos on container
      community.docker.docker_container_info:
        name: homepage
      register: homepage_result

    - name: test network starrnet
      docker_network_info:
        name: "{{ vpn_network }}"
      register: vpnnet_result
      when: homepage_result.exists

    - name: connect to starrnet if exists
      community.docker.docker_network:
        name: "{{ vpn_network }}"
        connected:
          - homepage
        appends: true
      when: vpnnet_result.exists
      ignore_errors: true
