---
- hosts: dockerlab 
  tasks:
    - name: test if homepage network exists
      docker_network_info:
        name: homenet
      register: vpnnet_result

    - name: create homepage network if not exists
      docker_network:
        name: homenet
      when: vpnnet_result.exists == false
    
    - name: deploy homepage container
      docker_container:
        name: homepage
        image: "ghcr.io/benphelps/homepage:latest"
        restart: true
        restart_policy: "unless-stopped"
        ports:
          - 3000:3000
        volumes:
          - "{{ config_root_dir }}/homepage:/config"
          - /var/run/docker.sock:/var/run/docker.soc # security issue - can we avoid?
        env:
          PUID: "{{ puid }}"
          PGID: "{{ pgid }}" 
          TZ: "{{ timezone }}"
        state: "{{ state }}"
        networks:
          - name: homenet
