---
- hosts: dockerlab 
  tasks:
    
    - name: deploy homepage container
      docker_container:
        name: homepage
        image: "ghcr.io/benphelps/homepage:latest"
        restart: true
        restart_policy: "unless-stopped"
        ports:
          - 3000:3000
        volumes:
          - "{{ config_root_dir }}/homepage:/config"
          - /var/run/docker.sock:/var/run/docker.soc # security issue - can we avoid?
        env:
          PUID: "{{ puid }}"
          PGID: "{{ pgid }}" 
          TZ: "{{ timezone }}"
        state: "{{ state }}"

    - name: test network starrnet
      docker_network_info:
        name: "{{ vpn_network }}"
      register: vpnnet_result

    - name: connect to starrnet if exists
      community.docker.docker_network:
        name: "{{ vpn_network }}"
        connected:
          - homepage
        appends: true
