- hosts: dockerlab
  vars_files:
    - variables/secrets.yaml
  tasks:
    - name: setup S3 scaleway alias 
      community.docker.docker_container_exec:
        container: minio
        command: mc alias set scaleway "{{ scw_endpoint }} {{ scw_access }} {{ scw_secret }}" 
