- hosts: dockerlab
  tasks:
    - name: start sync between one drive and local storage with rclone
      docker_container:
        name: rclonesync
        image: rclone/rclone
        volumes:
          - "{{ config_root_dir }}/rclone:/root/.config/rclone"
        command: sync /mnt/bigboy/media onedrive:media
