- hosts: dockerlab
  tasks:
    - name: start sync between one drive and local storage with rclone
      docker_container:
        name: rclonesync
        image: rclone/rclone
        env:
          PUID: "{{ puid }}" # var puid
          PGID: "{{ pgid }}" # var pgid
          TZ: "{{ timezone }}" # var timezone
        volumes:
          - "{{ config_root_dir }}/rclone:/config"
        command: rclone sync /mnt/bigboy/media onedrive:media
