- hosts: dockerlab
  tasks:
    - name: "lauch sync between {{ source }} and {{ destiantion }}"
      docker_container:
        name: rclone
        image: "rclone/rclone"
        recreate: "{{ recreate }}"
        restart: "{{ restart }}"
        state: "{{ state }}"
        restart_policy: unless_stopped
        env: 
          TZ: "{{ timezone }}"
          PUID: "{{ puid }}"
          PGID: "{{ pgid }}"
        volumes:
          - "{{ config_root_dir }}/rclone:/config/rclone"
          - "{{ data_dir }}:/data"
        command: "{{ cmd }} {{ source }} {{ destiantion}}"
