- hosts: dockerlab
  tasks:
    - name: "start sync from {{ source }} to {{ destination }} with rclone"
      docker_container:
        name: rclonesync
        image: rclone/rclone
        recreate: "{{ recreate }}"
        env:
          PUID: "{{ puid }}" # var puid
          PGID: "{{ pgid }}" # var pgid
          TZ: "{{ timezone }}" # var timezone
        volumes:
          - "{{ config_root_dir }}/rclone:/config/rclone"
          - "{{ data_dir }}/media:/data"
        command: "{{ cmd }} {{ source }} {{ destination }}"
