- hosts: controllers
  
  tasks:
    - name: test network
      docker_network_info:
        name: "{{ ansible_network }}"
      register: ansiblenet_result

    - name: create network if not exist
      docker_network:
        name: "{{ ansible_network }}"
      when: ansiblenet_result.exists == false

    - name: create folder config_root_dir if not exists
      file:  
        path: "{{ config_root_dir }}"
        state: directory
        mode: '755'

    - name: create bind mounts directory mysql first to avoid conflicting permissions
      file:
        path: "{{ config_root_dir }}/mysql"
        state: directory
        mode: '755'

    - name: create bind mounts directory semaphore to avoid conflicting permissions
      file:
        path: "{{ config_root_dir }}/semaphore"
        state: directory
        mode: '755'

    - name: launch mysql in container
      docker_container:
        name: "mysql"
        image: "mysql:8.0"
        hostname: "mysql"
        networks:
          - name: "{{ ansible_network }}"
        env:
          PUID: "{{ puid }}"
          PGID: "{{ pgid }}"
          TZ: "{{ timezone }}"
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
          MYSQL_DATABASE: semaphore
          MYSQL_USER: "{{ mysqluser }}"
          MYSQL_PASSWORD: "{{ mysqlpsswd }}"
        volumes:
          - "{{ config_root_dir }}/mysql:/var/lib/mysql"
        restart_policy: unless-stopped

    - name: "launch semaphore container"
      docker_container:
        name: "semaphore"
        image: "semaphoreui/semaphore:v2.9.30"
        ports:
          - "3002:3000"
        networks:
          - name: "{{ ansible_network }}"
        restart_policy: unless-stopped
        volumes:
          - "{{ config_root_dir }}/semaphore:/home/semaphore"
        env:
          PUID: "{{ puid }}" 
          PGID: "{{ pgid }}"
          TZ: "{{ timezone }}"
          SEMAPHORE_DB_USER: "{{ mysqluser }}"
          SEMAPHORE_DB_PASS: "{{ mysqlpsswd }}"
          SEMAPHORE_DB_HOST: "mysql" # for postgres, change to: postgres
          SEMAPHORE_DB_PORT: "3306" # change to 5432 for postgres
          SEMAPHORE_DB_DIALECT: "mysql" # for postgres, change to: postgres
          SEMAPHORE_DB: "semaphore"
          SEMAPHORE_PLAYBOOK_PATH: "/tmp/semaphore/"
          SEMAPHORE_ADMIN_PASSWORD: "{{ semaphorepsswd }}"
          SEMAPHORE_ADMIN_NAME: "admin"
          SEMAPHORE_ADMIN_EMAIL: "admin@localhost"
          SEMAPHORE_ADMIN: "admin"
          SEMAPHORE_ACCESS_KEY_ENCRYPTION: "{{ semaphorekey }}"

