- hosts: controllers
  
  tasks:
    - name: "launch semaphore container"
      docker_container:
        name: "semaphore"
        image: "semaphoreui/semaphore:latest"
        ports:
          - "3000:3000"
        restart_policy: unless-stopped
        volumes:
          - "{{ config_root_dir }}/semaphore:/home/semaphore"
        env:
          PUID: "{{ puid }}" 
          PGID: "{{ pgid }}"
          TZ: "{{ timezone }}"
          SEMAPHORE_DB_DIALECT: "bolt" # for postgres, change to: postgres
          SEMAPHORE_ADMIN_PASSWORD: "password"
          SEMAPHORE_ADMIN_NAME: "admin"
          SEMAPHORE_ADMIN_EMAIL: "admin@localhost"
          SEMAPHORE_ADMIN: "admin"

