---
- hosts: dockerlab

  vars_files:
    - "{{ vars-dir }}"/default_vars.yaml

  tasks:
    - name: deploy whoami container
      docker_container:
        name: whoami
        image: "traefik/whoami"
        state: "{{ state }}"
        command:
          - "--port=2001"
          - "--name=iamfoo"
        ports:
          - "2001:2001"

