- hosts: dockerlab
  become: true
  tasks:
  - name: install docker for debian based system
    block:
    - name: check if docker is already installed
      command: dpkg-query -l docker
      register: docker_check
        
    - name: install docker if not installed yet
      include_role:
        name: docker
      when: docker_check is failed

    rescue:
    - name: install docker whatever si ça merde
      include_role:
        name: docker
    
    when: ansible_facts['os_family'] == 'Debian'

  - name: install docker on arch based system
    community.general.pacman:
      name:
      - docker
      update_cache: yes
    when: ansible_facts['os_family'] == 'Archlinux'

  - name: enable and start docker service
    ansible.builtin.systemd:
      name: docker
      state: started
      enabled: true
      masked: false

