---
- hosts: dockerlab
  
  tasks:
  - name: install base server system for debian family os 
    block:
    - name: remove conflicting file to avoid ansible crash
      file:
        state: absent
        path: "/var/lib/dpkg/lock-frontend"
  
    - name: run apt update and apt upgrade
      apt:
        update_cache: yes
        upgrade: yes

    - name: Check if reboot is required
      ansible.builtin.stat:
        path: /var/run/reboot-required
        get_md5: no
      register: reboot_required_file

    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists

    - name: Remove dependencies no longer required after boot
      ansible.builtin.apt:
        autoremove: yes
  
    - name: Install some basic packages
      apt:
        pkg:
        - openssh-server
        - python3
        - git
        - curl
        - sudo
        - rclone
        - wget
        - ufw
        - neovim
        - dbus-user-session
        - fuse-overlayfs
        - slirp4netns
        update_cache: yes
        cache_valid_time: 3600

        - name: test if docker is already installed
          ansible.builtin.package:
            name: docker
            state: present
          check_mode: true
          register: docker_check

        - name: test if tailscale is already installed
          ansible.builtin.package:
            name: tailscale
            state: present
          check_mode: true
          register: tailscale_check

        - name: Remove dependencies no longer required after boot
          ansible.builtin.apt:
            autoremove: yes
      
    become: true
    when: ansible_facts['os_family'] == 'Debian'

  - name: install base system on arch family OS
    block:
      tasks:
      - name: update and upgrade
        community.general.pacman:
          update_cache: true
          upgrade: true

      - name: install base packages
        community.general.pacman:
          name:
            - neovim
            - wget
            - curl
            - openssh
            - python3
            - git
            - sudo
            - rclone
            - ufw
            - slirp4netns
            - fuse-overlayfs

        
    become: true
    when: ansible_facts['os_family'] == 'Archlinux'
