- hosts: dockerlab
  tasks:
    - name: start servarr pod
      containers.podman.podman_pod:
        name: servarr
        state: {{ state }}
        recreate: {{ recreate }}
        ports:
          - "9091:9091"
          - "51413:51413"
          - "51413:51413/udp"
