---
- name: copy nix.conf to /etc/nix
  ansible.builtin.copy:
    src: nixos/nix.conf
    dest: /etc/nix/nix.conf
    mode: 0644

- name: copy configuration.nix to /etc/nixos
  ansible.builtin.copy:
    src: nixos/configuration.nix
    dest: /etc/nixos/configuration.nix
    mode: 0644

- name: rebuild system avec switch
  ansible.builtin.shell: nixos-rebuild switch
