---
- hosts: debian
  become: true
  roles:
    - apt-upgrade

  tasks:
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - openssh-server
        - python3
        - git
        - curl
        - wget
