---
- hosts: endeavour
  become: true
  tasks:
    - name: upgrade pacman
      community.general.pacman:
        update_cache: true
        upgrade: true
    - name: install packages for hyprland
      community.general.pacman:
        name:
          - hyprland
          - eww
        state: present
