---
- hosts: ubuntu
  become: true
  tasks:
  
  - name: Download cuda pin
    ansible.builtin.get_url:
      url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
      dest: ~/cuda-ubuntu2204.pin
      mode: '0440'

  - name: Download cuda package
    ansible.builtin.get_url:
      url: https://developer.download.nvidia.com/compute/cuda/12.2.0/local_installers/cuda-repo-ubuntu2204-12-2-local_12.2.0-535.54.03-1_amd64.deb
      dest: ~/cuda-repo-ubuntu2204-12-2-local_12.2.0-535.54.03-1_amd64.deb
      mode: '0440'

  - name: prepare installation
    ansible.builtin.script: cuda-hashcat-2204.sh

  - name: "cuda installation"
    apt:
      name: "cuda"
      state: present
      update_cache: yes
